language: node_js

node_js:
  - lts/*

# In order to avoid double build on pull requests,
# only build on pushes on main and on pushes on pull requests
branches:
  only:
    - main

stages:
  - test
  - name: release
    if: type != pull_request AND branch = main

jobs:
  include:
    - stage: test
      script:
        - npx danger ci
        - yarn test

    - stage: release
      script:
        - npx semantic-release
