on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn

      - name: Danger JS
        uses: danger/danger-js@X.Y.Z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: yarn test
        name: Test

  release:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v3

      # Install NPM dependencies
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn

      - name: Release
        run: npx semantic-release